import type { Metadata } from "next";
import "./globals.css";
import ApolloWrapper from "@/utils/apolloClient";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<ApolloWrapper>
				<body className="relative min-h-[100dvh] flex flex-col items-center justify-center overflow-x-hidden">
					{children}
				</body>
			</ApolloWrapper>
		</html>
	);
}
